### PR TITLE
Support for Basic Auth

### PR DESCRIPTION
**Pull request by drinks**
Grabbing `URI#host()` from the supplied connection strings stripped out things like protocol and basic auth, making it impossible to connect to an authenticated cluster. This PR gets the connection URL by lopping off the path rather than grabbing only the host, along with a little cleanup for the linter.

### CODE REVIEW

**Comment by garbin** [comment]
Sounds great! Like the others, I need double check you've do fully tested, Because this project has not unit tests yet, and after I merged it, I will push it to npm ASAP. wait your answer, I will merged it after you say yes!

**Comment by drinks** [comment]
I just used it to reindex a few dozen indices in production. I haven't confirmed HTTPS works since the ES client takes a slew of SSL config options that won't be supplied. I have an index to re-run tomorrow and will try it with https. If the defaults work out of the box we should be g2g.

Also, now that you mention it, I probably need to handle querystrings so I'll switch to a regexp-based method of extracting the host and add to this PR when ready.

**Comment by drinks** [comment]
Ok, confirmed working with SSL, and there's an update included to pull out querystrings from the connection string given to the ES client

**Comment by garbin** [comment]
Sorry, so late to process your PR, I was been away from github in the last two days.
PR is merged, and the new version v1.1.8 is pushed and  available on npm now. Thank you for your contribution.

**Pull request merged**
